---
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/
install:
  - pip install -r requirements.lock --cache-dir $HOME/.pip-cache
env: PYTHONPATH=.:$PYTHONPATH
before_script:
script:
  - fab polish:ci
